'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Claim
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''windowMemberSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowMemberSearch As Global.Infragistics.Web.UI.LayoutControls.WebDialogWindow
    
    '''<summary>
    '''panelMembSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelMembSearch As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnMembSearchCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMembSearchCancel As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''txtMembId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMembId As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMembDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMembDOB As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMembLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMembLastName As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMembFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMembFirstName As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''btnMembSearchRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMembSearchRefresh As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnMembSearchGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMembSearchGrid As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gridMemb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMemb As Global.Infragistics.Web.UI.GridControls.WebDataGrid
    
    '''<summary>
    '''windowDiagCodeSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowDiagCodeSearch As Global.Infragistics.Web.UI.LayoutControls.WebDialogWindow
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnDiagSearchCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiagSearchCancel As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''tabDiagnosisCodeSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabDiagnosisCodeSearch As Global.Infragistics.Web.UI.LayoutControls.WebTab
    
    '''<summary>
    '''panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCode As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''btnDiagSearchRefresh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiagSearchRefresh1 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnDiagSearchGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiagSearchGrid As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''panel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtICD9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtICD9 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''btnDiagSearchRefresh2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiagSearchRefresh2 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnSearchICD9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchICD9 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''gridDiagCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridDiagCode As Global.Infragistics.Web.UI.GridControls.WebDataGrid
    
    '''<summary>
    '''updatePanelTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePanelTest As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''progressBarClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents progressBarClaim As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtProgressClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgressClaim As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''progressBarDiagCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents progressBarDiagCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtProgressDiagCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgressDiagCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''progressBarProcedures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents progressBarProcedures As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtProgressProc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgressProc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCheckClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckClaim As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblIpa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIpa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''radiobtnClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radiobtnClaim As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''radiobtnEncounter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radiobtnEncounter As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblRequestDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''panelMemberPre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelMemberPre As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtTableMembId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTableMembId As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''btnMembSearchDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMembSearchDialog As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''panelMemberPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelMemberPost As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblMembId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMembId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbProvider As Global.Infragistics.Web.UI.ListControls.WebDropDown
    
    '''<summary>
    '''cmbPOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPOS As Global.Infragistics.Web.UI.ListControls.WebDropDown
    
    '''<summary>
    '''cmbOutcomeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbOutcomeCode As Global.Infragistics.Web.UI.ListControls.WebDropDown
    
    '''<summary>
    '''cmbAuthNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAuthNo As Global.Infragistics.Web.UI.ListControls.WebDropDown
    
    '''<summary>
    '''txtPovClaimNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPovClaimNo As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacility As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''btnDiagSearchDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiagSearchDialog As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCheckDiag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckDiag As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''txtDiagCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiagCode As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''btnDiagCodeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiagCodeAdd As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''gridDiag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridDiag As Global.Infragistics.Web.UI.GridControls.WebDataGrid
    
    '''<summary>
    '''btnSearchProcDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchProcDialog As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCheckProc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckProc As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''txtProcedure1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProcedure1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtQty1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQty1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtBilled1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBilled1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtDiagRef1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiagRef1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtFromDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFromDate1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtFromTime1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFromTime1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtToDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToDate1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtToTime1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToTime1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMod11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMod11 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMod12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMod12 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMod13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMod13 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMod14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMod14 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor2 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor3 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor4 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor5 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor6 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor7 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor8 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor9 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor10 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor11 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor12 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
End Class
