'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClaimSearch
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''WebTab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTab1 As Global.Infragistics.Web.UI.LayoutControls.WebTab
    
    '''<summary>
    '''panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtClaimNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimNo1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMemFirst1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMemFirst1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMemLast1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMemLast1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtIdNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdNo1 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''cmbStatus1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStatus1 As Global.Infragistics.Web.UI.ListControls.WebDropDown
    
    '''<summary>
    '''btnHelp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHelp1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnRefresh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnSearch1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtClaimNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimNo2 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMemFirst2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMemFirst2 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtMemLast2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMemLast2 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''txtIdNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdNo2 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''cmbProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbProvider As Global.Infragistics.Web.UI.ListControls.WebDropDown
    
    '''<summary>
    '''cmbStatus2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStatus2 As Global.Infragistics.Web.UI.ListControls.WebDropDown
    
    '''<summary>
    '''datepicker3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datepicker3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''datepicker1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datepicker1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''datepicker2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datepicker2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnHelp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHelp2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnRefresh2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnSearch2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnHealthPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHealthPlan As Global.Infragistics.Web.UI.ListControls.WebDropDown
    
    '''<summary>
    '''WebTextEditor11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor11 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebTextEditor12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebTextEditor12 As Global.Infragistics.Web.UI.EditorControls.WebTextEditor
    
    '''<summary>
    '''WebDialogWindow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebDialogWindow1 As Global.Infragistics.Web.UI.LayoutControls.WebDialogWindow
    
    '''<summary>
    '''WebDataGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebDataGrid1 As Global.Infragistics.Web.UI.GridControls.WebDataGrid
End Class
